export const actionTypes = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
  LOAD_MORE_USERS: 'LOAD_MORE_USERS',
  ADVANCE_PAGE: 'ADVANCE_PAGE',
  END_OF_LIST: 'END_OF_LIST',
};
